apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "fast-api-app.fullname" . }}-secrets"
type: Opaque
data:
  mariadb-user: {{ .Values.mysql.auth.username | b64enc }}
  mariadb-password: {{ .Values.mysql.auth.password | b64enc }}
  mariadb-root-password: {{ .Values.mysql.auth.rootPassword | b64enc }}